---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    ingress.kubernetes.io/secure-backends: "true"
  name: {{.DASHBOARD_NAME}}
spec:
  rules:
  - host: {{.DASHBOARD_NAME}}.notprod.homeoffice.gov.uk
    http:
      paths:
      - backend:
          serviceName: {{.DASHBOARD_NAME}}
          servicePort: https
        path: /
  tls:
  - hosts:
    - {{.DASHBOARD_NAME}}.notprod.homeoffice.gov.uk
    - www.{{.DASHBOARD_NAME}}.notprod.homeoffice.gov.uk
    secretName: external-tls
